version: "3"

services:
    rabbitmq_server:
        container_name: fibonacci_rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:${RABBITMQ_PORT}
            - 15672:15672 
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    postgres_db:
        container_name: fibonacci_postgres
        image: postgres
        ports:
            - 5432:${POSTGRES_PORT}
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
    generator_service:
        container_name: fibonacci_generator
        build: generator
        depends_on:
            - rabbitmq_server
        restart: on-failure
    ingest_service:
        container_name: fibonacci_ingest
        build: ingest
        depends_on:
            - rabbitmq_server
            - postgres_db
        restart: on-failure
    api_service:
        container_name: fibonacci_api
        build: api
        ports:
            - 8000:8000
        depends_on:
            - rabbitmq_server
            - postgres_db
        restart: on-failure
    